name: Python Style Checks

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # or your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle pydocstyle

    - name: Run pycodestyle
      run: |
        echo "Running pycodestyle..."
        pycodestyle .

    - name: Run pydocstyle
      run: |
        echo "Running pydocstyle..."
        pydocstyle . --match='.*\.py'
